app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='home'),
    path('register/', views.register, name='register'),
    path('party/', views.party, name='party'),
    path('chosen-one/', views.welcomeParty, name='chosen'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models

# Create your models here.

# TODO create parties as models and associate each user with each

app/forms.py
from django.contrib.auth.models import User
from django import forms


class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password',
        )

app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


# Create your views here.


def index(request):
    if request.user.is_authenticated:
        return render(request, 'parties.html')
    else:
        return render(request, 'registration/login.html')


@login_required(login_url='/accounts/login/')
def party(request):
    return render(request, 'parties.html')


def welcomeParty(request):
    return render(request, 'welcome.html')


def register(request):
    form = UserCreationForm
    context = {
        'form': form,
    }
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']

        user = User.objects.create_user(username, email, password)
        user.save()
        login(request, user)
        return render(request, 'parties.html')
    return render(request, 'register.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block title %}

    {% endblock title %}

</head>
<body>
<section>
    <nav class="navbar mb-4" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="">
                <img src="../static/images/logo.png" style="object-fit: contain;">
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
               data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item">
                    Home
                </a>

                <a class="navbar-item">
                    All Parties
                </a>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        More
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item">
                            About
                        </a>
                        <a class="navbar-item">
                            Contact
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item">
                            Report an issue
                        </a>
                    </div>
                </div>
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        {% if user.is_authenticated %}
                            <a class="button is-light" href="{% url 'logout' %}">
                                Log Out
                            </a>
                        {% else %}
                            <a class="button is-primary" href="{% url 'app:register' %}">
                                <strong>Sign up</strong>
                            </a>
                            <a class="button is-light" href="{% url 'login' %}">
                                Log In
                            </a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </nav>
</section>


{% block content %}

{% endblock content %}
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    <title>Home</title>
{% endblock title %}


{% block content %}

    <section class="mt-6">
        <form action="">
            <div class="column is-half is-offset-one-quarter">

                <div class="field">
                    <label class="label">Username or Email</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="Text input">
                    </div>
                </div>

                <div class="field">
                    <label class="label">Password</label>
                    <p class="control has-icons-left">
                        <input class="input" type="password" placeholder="Password">
                        <span class="icon is-small is-left">
                            <i class="fas fa-lock"></i>
                        </span>
                    </p>
                </div>

                {% if form.errors %}
                    <p class="help is-danger">Your username and password didn't match. Please try again.</p>
                {% endif %}

                <div class="field is-grouped mt-4">
                    <div class="control">
                        <button class="button is-link">Continue</button>
                    </div>
                    <div class="control">
                        <button class="button is-link is-light">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
    </section>

{% endblock content %}

templates/parties.html
{% extends 'base.html' %}

{% block content %}
<section class="flex mt-6">
    <ul class="deck preload">
        <li class="card">
            <div class="content">
                <img src="../static/images/Jubilee_Party.png" alt="">
            </div>
        </li>
        <li class="card">
            <div class="content">
                <img src="../static/images/kanu.jpg" alt="">
            </div>
        </li>
        <li class="card">
            <div class="content">
                <img src="../static/images/NASA.png" alt="">
            </div>
        </li>
        <li class="card">
            <div class="content">
                <img src="../static/images/flag.gif" alt="">
            </div>
        </li>
    </ul>
</section>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        load();
    });
</script>
{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
    <title>Sign Up</title>
{% endblock %}

{% block content %}
    <section class="mt-6">
        <form action="" method="post">
            {% csrf_token %}
            <div class="column is-half is-offset-one-quarter">

                <div class="field">
                    <label class="label">{{ form.username.label_tag }}</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="Text input" name="{{ form.username.html_name }}">
                    </div>
                </div>

                <div class="field">
                    <label class="label">{{ form.email.label_tag }}</label>
                    <div class="control has-icons-left has-icons-right">
                        <input class="input is-danger" type="email" placeholder="Email input"
                               id="email" name="{{ form.email.html_name }}">
                        <span class="icon is-small is-left">
                        <i class="fas fa-envelope"></i>
                    </span>
                        <span class="icon is-small is-right">
                        <i class="fas fa-exclamation-triangle"></i>
                    </span>
                    </div>
                    <p class="help is-danger" id="help">This email is invalid</p>
                </div>

                <div class="field">
                    <p class="control has-icons-left">
                        <input class="input" type="password" placeholder="Password"
                               name="{{ form.password.html_name }}">
                        <span class="icon is-small is-left">
                            <i class="fas fa-lock"></i>
                        </span>
                    </p>
                </div>

                <div class="field">
                    <div class="control">
                        <label class="checkbox">
                            <input type="checkbox">
                            I agree to the <a href="#">terms and conditions</a>
                        </label>
                    </div>
                </div>

                <div class="field is-grouped mt-4">
                    <div class="control">
                        <button class="button is-link">Continue</button>
                    </div>
                    <div class="control">
                        <button class="button is-link is-light">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
    </section>
{% endblock %}

templates/welcome.html
{% extends 'base.html' %}

{% block title %}
    <title>Welcome to {{ party }}</title>
{% endblock %}

{% block content %}
    <div class="mt-4 container">
        <p>
            Thank you for choosing {{ party }}
        </p>
    </div>
{% endblock %}